// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIcsB3Xh7aGGuEw14RvKEXrbjGxCTjdM',
    appId: '1:391695718626:web:f0e546a5312d49593626bb',
    messagingSenderId: '391695718626',
    projectId: 'study-mode-78bf6',
    authDomain: 'study-mode-78bf6.firebaseapp.com',
    storageBucket: 'study-mode-78bf6.firebasestorage.app',
    measurementId: 'G-GXS27H3EVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7NuOMpv-Vdo8wAEJWYvam5-O9d9TBqko',
    appId: '1:391695718626:android:34dc3017b86ad2a63626bb',
    messagingSenderId: '391695718626',
    projectId: 'study-mode-78bf6',
    storageBucket: 'study-mode-78bf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkHhv1ZnFoPc1DlobeQDJfBrsfvSiRgvE',
    appId: '1:391695718626:ios:9ea89e17cf5daf933626bb',
    messagingSenderId: '391695718626',
    projectId: 'study-mode-78bf6',
    storageBucket: 'study-mode-78bf6.firebasestorage.app',
    iosBundleId: 'com.studymode.app.studyModeV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkHhv1ZnFoPc1DlobeQDJfBrsfvSiRgvE',
    appId: '1:391695718626:ios:9ea89e17cf5daf933626bb',
    messagingSenderId: '391695718626',
    projectId: 'study-mode-78bf6',
    storageBucket: 'study-mode-78bf6.firebasestorage.app',
    iosBundleId: 'com.studymode.app.studyModeV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLIcsB3Xh7aGGuEw14RvKEXrbjGxCTjdM',
    appId: '1:391695718626:web:e21aa73e32a572053626bb',
    messagingSenderId: '391695718626',
    projectId: 'study-mode-78bf6',
    authDomain: 'study-mode-78bf6.firebaseapp.com',
    storageBucket: 'study-mode-78bf6.firebasestorage.app',
    measurementId: 'G-94XEBMXW7D',
  );

}